### ISSUE TITLE
PA Review: Third-Party Accounts

### ISSUE THREAD

**Issue by znrm** [znrm/sage#3]
Backend:
- [x] DB: Providers table, accounts
- [x] Models: Providers model, accounts model, associations
- [x] Controllers: CRUD for providers and accounts
- [x] Views: JSON output for API

 Actions, reducers, components
- [x]  issue #5 

Styling:
- [x] Overview page styling
- [x] Main accounts page styling
- [x] New Accounts page styling

Misc.
- [x] Smooth, bug-free navigation
- [x] Adequate providers seeds
- [x] Demo user accounts seeds

**Comment by znrm** [comment]
This feature has now been fully implemented.with the exception of the main accounts page (for viewing account details, editing accounts, etc.), Users can create accounts and they can see a summary of their accounts. I'd like to get some feedback before finishing the last portion of this. Thanks!

**Comment by znrm** [comment]
The main accounts page, which allows users to edit or delete their accounts, has now been implemented. Let me know if you find any issues on that page (or others). Thanks!

**Comment by s-pangburn** [comment]
Looks to be good! Your error message for the numericality validation of the balance is a little awkward-sounding, but I think that's just what Rails gives you, no? This feature should be considered complete and you should move on 🙂
